language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 3.1.100   # this is the version number of the .Net Core SDK, not the .Net Core Runtime
branches:  
  only:
    - master
before_install:
  - sudo apt-get install dotnet-sdk-2.1 # Only need this line because BundlerMinifier.Core has a dependency on .net core 2
before_script:
  - npm install -g bower
  - chmod a+x ./scripts/build.sh
script:
  - ./scripts/build.sh --quiet verify
before_deploy:
  - mkdir -p code-drop
  - pushd /home/travis/build/jmarsalis/dotnet-core-sandbox/ # need to be in the directory with appspec.yml so it will be at the root of the zip
  - zip -r /tmp/latest.zip /tmp/build-artifacts/* ./appspec.yml ./scripts/restart-website.sh # appspec.yml and referenced scripts have to be at the root of the package being created
  - popd
  - mv /tmp/latest.zip code-drop/latest.zip
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: code-drop
  upload_dir: sandbox-artifacts
  skip_cleanup: true
  on: &2
    repo: jmarsalis/dotnet-core-sandbox
  bucket: being-there
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: being-there
  key: sandbox-artifacts/latest.zip
  bundle_type: zip
  application: Mercury
  deployment_group: Sandbox
  region: us-east-1
  on: *2